services:
  catalogdb:
   image: postgres

  Basketgdb:
   image: postgres

  distributechache:
    image: redis

 

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: services/Discount.GRPC/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


    


